version: "3.8"
services:
  sqlserver:
    container_name: sqlserver
    build: ./config/mssql
    user: root
    ports:
      - 1433:1433
    volumes:
      - ./db/:/var/opt/mssql/data
   
  app:
    build: ./config/php
    container_name: php-app
    working_dir: /var/www/html
    volumes:
      - ./www/:/var/www/html
    depends_on:
      - sqlserver

  nginx:
    image: nginx:alpine
    container_name: php-nginx
    ports:
      - 80:80
    volumes:
      - ./www/:/var/www/html
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
